---
kind: Namespace
apiVersion: v1
metadata:
  name: cpu-labeler
spec: {}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cpu-labeler
  namespace: cpu-labeler

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cpu-labeler-ds
rules:
- apiGroups: ["*"]
  resources: ["nodes"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cpu-labeler-ds
subjects:
- kind: ServiceAccount
  name: cpu-labeler
  namespace: cpu-labeler
roleRef:
  kind: ClusterRole
  name: cpu-labeler-ds
  apiGroup: rbac.authorization.k8s.io

---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: cpu-model-host-labeler
  namespace: cpu-labeler
  labels:
    k8s-app: cpu-model-host-labeler
spec:
  selector:
    matchLabels:
      name: cpu-model-host-labeler
  template:
    metadata:
      labels:
        name: cpu-model-host-labeler
    spec:
      containers:
        - name: labeler
          image: 'jpapejr/cpu-labeler:latest'
          command: ["/usr/local/bin/script.sh"]  
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 32Mi
          env:
          - name: NODE
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      serviceAccount: cpu-labeler



